#+title: Structural design applications
#+setupfile: index.setup
#+include: "navbar.org"

* Description
This is a website created by James Maguire to solve simple structural engineering design problems. There is no warranty of correctness of these applications and results must be checked by other methods by an experienced engineer if they are to be used for design purposes.

* Usage
Input boxes with an @@html:<input value="orange" readonly></input>@@ background are design inputs. Once an input is changed, the indicator on the top right of the page will show that the analysis must be re-run. To run the analysis press =ENTER= in any of the input fields.


* Todos                                                            :noexport:
** TODO Page: second moment of area
** TODO Page: Geo properties
** TODO Page: beam bending formulae
** TODO Page: Beam moment capacity (+ drawing)

** TODO Search/filter navbar
** TODO Update Up to date icon css
** TODO Fix sub/super scripts
** TODO Update navbar css
** TODO Create output textbox
