#+title: Reinforced Concrete Beam
#+subtitle: Based on AS3600 2018

#+setupfile: post.setup
#+HTML_HEAD: <script type="text/javascript" src="../static/rcbeam.js" defer></script>
#+include: "../statusicon.org"

* Image

{{{div(beamFigure)}}}

* Beam parameters

Beam width {{{span(i_B)}}}

Beam depth {{{span(i_D)}}}

Top reo {{{span(i_nbc)}}} {{{span(i_dbc)}}}

Bottom reo {{{span(i_nbt)}}} {{{span(i_dbt)}}}

Edge bars {{{span(i_nbe)}}} {{{span(i_dbe)}}}

Ties {{{span(i_dbs)}}} {{{span(i_dbspc)}}}

Cover {{{span(i_c)}}}

Effective depth {{{span(o_d)}}}

Axis depth {{{span(o_a)}}}

Area tensile steel {{{span(o_Ast)}}}

Area compression steel {{{span(o_Asc)}}}

* Material properties

Concrete strength {{{span(i_fc)}}}

Concrete ult. strain, \varepsilon_{cu} {{{span(i_ecu)}}}

\alpha_2 {{{span(o_alpha2)}}}

\gamma {{{span(o_gamma)}}}

Steel strength {{{span(i_fsy)}}}

Steel modulus {{{span(i_Es)}}}

Steel ult. strain, \varepsilon_{su} {{{span(o_esu)}}}

* Loading

Applied moment, M* {{{span(i_Mstar)}}}

Applied shear, V* {{{span(i_Vstar)}}}

* Bending capacity

Neutral axis parameter, k_u {{{span(o_ku)}}}

Plastic neutral axis, d_n {{{span(o_dn)}}}

Moment capacity, M_{uo} {{{span(o_Muo)}}}

Capacity reduction factor, \Phi {{{span(o_phi)}}}

Design moment capacity, \Phi{}M_{uo} {{{span(o_phiMuo)}}}

Moment check, M*/\Phi{}M_{uo} {{{span(momentCheck)}}}

* Minimum strength

Section modulus, Z {{{span(o_Z)}}}

Concrete flex.ten. strength, f'_{ct.f} {{{span(o_fctf)}}}

Minimum bending strength, M_{uo,min} {{{span(o_Muomin)}}}

Min strength check, M_{uo,min}/M_{uo} {{{span(momentminCheck)}}}

* Shear strength

Shear reo legs {{{span(i_nlegs)}}}, angle {{{span(i_alphav)}}}
 
Transverse reo, A_{sv} {{{span(o_Asv)}}}

A_{sv.min} {{{span(o_Asvmin)}}}, required? {{{span(o_Asvminreq)}}}

\epsilon_x {{{span(o_epsilonx)}}}, \theta_v {{{span(o_thetav)}}}, k_v {{{span(o_kv)}}}

Shear capacity (concrete), V_{uc} {{{span(o_Vuc)}}}

Shear capacity (steel), V_{us} {{{span(o_Vus)}}}

Capacity reduction factor, \Phi {{{span(o_phiV)}}}

Web crushing, \Phi{}V_{u.max} {{{span(o_phiVumax)}}}

Shear capacity, \Phi{}Vu {{{span(o_phiVu)}}}

Shear check, V*/\Phi{}V_{u} {{{span(shearCheck)}}}

* Export on save                                                   :noexport:
;; Local Variables:
;; eval: (add-hook 'after-save-hook 'org-html-export-to-html nil t)
;; End:
